
export const nationalities = [
    { label: "Afghan", value: "AFGHAN" },
    { label: "Albanian", value: "ALBANIAN" },
    { label: "Algerian", value: "ALGERIAN" },
    { label: "American", value: "AMERICAN" },
    { label: "Andorran", value: "ANDORRAN" },
    { label: "Angolan", value: "ANGOLAN" },
    { label: "Argentinian", value: "ARGENTINIAN" },
    { label: "Armenian", value: "ARMENIAN" },
    { label: "Australian", value: "AUSTRALIAN" },
    { label: "Austrian", value: "AUSTRIAN" },
    { label: "Azerbaijani", value: "AZERBAIJANI" },
    { label: "Bahamian", value: "BAHAMIAN" },
    { label: "Bahraini", value: "BAHRAINI" },
    { label: "Bangladeshi", value: "BANGLADESHI" },
    { label: "Barbadian", value: "BARBADIAN" },
    { label: "Belarusian", value: "BELARUSIAN" },
    { label: "Belgian", value: "BELGIAN" },
    { label: "Belizean", value: "BELIZEAN" },
    { label: "Beninese", value: "BENINESE" },
    { label: "Bhutanese", value: "BHUTANESE" },
    { label: "Bolivian", value: "BOLIVIAN" },
    { label: "Bosnian", value: "BOSNIAN" },
    { label: "Botswanan", value: "BOTSWANAN" },
    { label: "Brazilian", value: "BRAZILIAN" },
    { label: "British", value: "BRITISH" },
    { label: "Bruneian", value: "BRUNEIAN" },
    { label: "Bulgarian", value: "BULGARIAN" },
    { label: "Burkinabe", value: "BURKINABE" },
    { label: "Burmese", value: "BURMESE" },
    { label: "Burundian", value: "BURUNDIAN" },
    { label: "Cambodian", value: "CAMBODIAN" },
    { label: "Cameroonian", value: "CAMEROONIAN" },
    { label: "Canadian", value: "CANADIAN" },
    { label: "Cape Verdean", value: "CAPE_VERDEAN" },
    { label: "Central African", value: "CENTRAL_AFRICAN" },
    { label: "Chadian", value: "CHADIAN" },
    { label: "Chilean", value: "CHILEAN" },
    { label: "Chinese", value: "CHINESE" },
    { label: "Colombian", value: "COLOMBIAN" },
    { label: "Comorian", value: "COMORIAN" },
    { label: "Congolese", value: "CONGOLESE" },
    { label: "Costa Rican", value: "COSTA_RICAN" },
    { label: "Croatian", value: "CROATIAN" },
    { label: "Cuban", value: "CUBAN" },
    { label: "Cypriot", value: "CYPRIOT" },
    { label: "Czech", value: "CZECH" },
    { label: "Danish", value: "DANISH" },
    { label: "Djiboutian", value: "DJIBOUTIAN" },
    { label: "Dominican", value: "DOMINICAN" },
    { label: "Dutch", value: "DUTCH" },
    { label: "Ecuadorian", value: "ECUADORIAN" },
    { label: "Egyptian", value: "EGYPTIAN" },
    { label: "Emirati", value: "EMIRATI" },
    { label: "Equatorial Guinean", value: "EQUATORIAL_GUINEAN" },
    { label: "Eritrean", value: "ERITREAN" },
    { label: "Estonian", value: "ESTONIAN" },
    { label: "Ethiopian", value: "ETHIOPIAN" },
    { label: "Fijian", value: "FIJIAN" },
    { label: "Finnish", value: "FINNISH" },
    { label: "French", value: "FRENCH" },
    { label: "Gabonese", value: "GABONESE" },
    { label: "Gambian", value: "GAMBIAN" },
    { label: "Georgian", value: "GEORGIAN" },
    { label: "German", value: "GERMAN" },
    { label: "Ghanaian", value: "GHANAIAN" },
    { label: "Greek", value: "GREEK" },
    { label: "Guatemalan", value: "GUATEMALAN" },
    { label: "Guinean", value: "GUINEAN" },
    { label: "Haitian", value: "HAITIAN" },
    { label: "Honduran", value: "HONDURAN" },
    { label: "Hungarian", value: "HUNGARIAN" },
    { label: "Icelander", value: "ICELANDER" },
    { label: "Indian", value: "INDIAN" },
    { label: "Indonesian", value: "INDONESIAN" },
    { label: "Iranian", value: "IRANIAN" },
    { label: "Iraqi", value: "IRAQI" },
    { label: "Irish", value: "IRISH" },
    { label: "Israeli", value: "ISRAELI" },
    { label: "Italian", value: "ITALIAN" },
    { label: "Jamaican", value: "JAMAICAN" },
    { label: "Japanese", value: "JAPANESE" },
    { label: "Jordanian", value: "JORDANIAN" },
    { label: "Kazakhstani", value: "KAZAKHSTANI" },
    { label: "Kenyan", value: "KENYAN" },
    { label: "Kuwaiti", value: "KUWAITI" },
    { label: "Lao", value: "LAO" },
    { label: "Latvian", value: "LATVIAN" },
    { label: "Lebanese", value: "LEBANESE" },
    { label: "Libyan", value: "LIBYAN" },
    { label: "Lithuanian", value: "LITHUANIAN" },
    { label: "Malaysian", value: "MALAYSIAN" },
    { label: "Maldivian", value: "MALDIVIAN" },
    { label: "Malian", value: "MALIAN" },
    { label: "Maltese", value: "MALTESE" },
    { label: "Mexican", value: "MEXICAN" },
    { label: "Mongolian", value: "MONGOLIAN" },
    { label: "Moroccan", value: "MOROCCAN" },
    { label: "Nepalese", value: "NEPALESE" },
    { label: "New Zealander", value: "NEW_ZEALANDER" },
    { label: "Nigerian", value: "NIGERIAN" },
    { label: "North Korean", value: "NORTH_KOREAN" },
    { label: "Norwegian", value: "NORWEGIAN" },
    { label: "Pakistani", value: "PAKISTANI" },
    { label: "Palestinian", value: "PALESTINIAN" },
    { label: "Polish", value: "POLISH" },
    { label: "Portuguese", value: "PORTUGUESE" },
    { label: "Qatari", value: "QATARI" },
    { label: "Romanian", value: "ROMANIAN" },
    { label: "Russian", value: "RUSSIAN" },
    { label: "Saudi Arabian", value: "SAUDI_ARABIAN" },
    { label: "South African", value: "SOUTH_AFRICAN" },
    { label: "Spanish", value: "SPANISH" },
    { label: "Sri Lankan", value: "SRI_LANKAN" },
    { label: "Syrian", value: "SYRIAN" },
    { label: "Thai", value: "THAI" },
    { label: "Turkish", value: "TURKISH" },
    { label: "Ukrainian", value: "UKRAINIAN" },
    { label: "Vietnamese", value: "VIETNAMESE" }
];
