const ProtectedRoutes: Record<string, string[]> = {
    "/dashboard": ["show_database_stats"],
    "/flights": ["can_search_flight"],
    "": ["can_view_reservations"],
    "/reservation/my-voids": ["can_view_my_void_request"],
    "/organizations/branches": ["can_view_branches"],
    "/organizations/agencies": ["can_view_agencies"],
    "/organizations/employees": ["can_view_employees"],
    "/settings/bank-accounts": ["can_view_bank_accounts_setting"],
    "/settings/airline-margins": ["can_view_airline_margins_setting"],
    "/settings/connectors": ["can_view_suppliers_setting"],
    "/settings/suppliers": ["can_view_airlines_setting"],
    "/settings/airlines": ["can_view_airports_setting"],
    "/settings/airports": ["can_view_airports_setting"],
    "/settings/countries": ["can_view_cities_settings"],
    "/settings/news": ["can_view_news_setting"],
    "/accounts/agency-deposites": ["can_view_agency_deposites"],
    "/accounts/branch-deposites": ["can_view_branch_deposites"],
    "/reports/sales-report": ["can_view_sales_report"],
    "/reports/transaction-history": ["can_view_transaction_history"],
    "/reports/unused-tickets": ["can_view_un_used_tickets"],
    "/notifications": ["can_view_notifications"],
    "/reservation/my-bookings": ["can_view_my_bookings"],
    "/dashboard": ["can_view_sub_agents"],
    "/finance/ag-pricing": ["can_view_ag_pricing"],
    "/finance/payment-request": ["can_view_payment_request"],
    "/organization/passenger-management": ["can_view_passenger_management"],
};